# Etapa de build
FROM golang:1.20-alpine AS builder
WORKDIR /app

# Baixar dependências
COPY go.mod go.sum ./
RUN go mod download

# Copiar o código-fonte
COPY . .

# Construir a aplicação
RUN go build -o myapp .

# Etapa final
FROM alpine:3.18
WORKDIR /app

# Copiar o binário da etapa de build
COPY --from=builder /app/myapp .

# Executar a aplicação
CMD ["./myapp"]